/**
 * @format
 */
const QueryKeys = {
  homeFeed: 'homeFeed',
  userFeed: 'userFeed',
  userMedia: 'userMedia',
  userFollowing: 'userFollowing',
  userProfileDetails: 'userProfileDetails',
  useFollowers: 'useFollowers',
  useFollowBackUser: 'useFollowBackUser',
  groupsList: 'groupsList',
  notifications: 'notifications',
  viewNotifications: 'viewNotifications',
  groupProfileDetails: 'groupProfileDetails',
  groupFeed: 'groupFeed',
  groupMedia: 'groupMedia',
  groupMemberCheck: 'groupMemberCheck',
  groupMembers: 'groupMembers',
  comments: 'comments',
  settingKey: 'settingKey',
  groupMakeAdmin: 'groupMakeAdmin',
  groupRemoveAdmin: 'groupRemoveAdmin',
  businessList: 'businessList',
  businessProfile: 'businessProfile',
  businessProfileDetails: 'businessProfileDetails',
  businessFeed: 'businessFeed',
  businessDetails: 'businessDetails',
  businessMemberCheck: 'businessMemberCheck',
  businessMedia: 'businessMedia',
  businessMembers: 'businessMembers',
  businessPageMembers: 'businessPageMembers',
  eventList: 'eventList',
  eventProfileDetails: 'eventProfileDetails',
  eventFeed: 'eventFeed',
  eventMembers: 'eventMembers',
  eventMemberCheck: 'eventMemberCheck',
  useEventAttendees: 'useEventAttendees',
  privacySetting: 'privacySetting',
  postFeed: 'postFeed',
  notificationSettings: 'notificationSettings',
  postComments: 'postComments',
  channelList: 'channelList',
  oneToOneHistory: 'oneToOneHistory',
  categories: 'categories',
  subCategories: 'subCategories',
  recommendations: 'recommendations',
  searchUser: 'searchUser',
  stepSetting: 'stepSetting',
  profileMessengerStatus: 'profileMessengerStatus',
  singlePostData: 'singlePostData',
  searchApi: 'searchApi',
  connectionAll: 'connectionAll',
  connectionPeople: 'connectionPeople',
  searchAll: 'searchAll',
};

export type QueryKeysType = keyof typeof QueryKeys;

export {QueryKeys};
