export enum UserTypes {
  SIGNUP = 'SIGNUP',
  SIGNUP_PENDING = 'SIGNUP_PENDING',
  SIGNUP_FULFILLED = 'SIGNUP_FULFILLED',
  SIGNUP_REJECTED = 'SIGNUP_REJECTED',

  LOGIN = 'LOGIN',
  LOGIN_PENDING = 'LOGIN_PENDING',
  LOGIN_FULFILLED = 'LOGIN_FULFILLED',
  LOGIN_REJECTED = 'LOGIN_REJECTED',

  GET_PROFILE = 'GET_PROFILE',
  GET_PROFILE_PENDING = 'GET_PROFILE_PENDING',
  GET_PROFILE_FULFILLED = 'GET_PROFILE_FULFILLED',
  GET_PROFILE_REJECTED = 'GET_PROFILE_REJECTED',

  GET_MESSENGER_PROFILE = 'GET_MESSENGER_PROFILE',
  GET_MESSENGER_PROFILE_PENDING = 'GET_MESSENGER_PROFILE_PENDING',
  GET_MESSENGER_PROFILE_FULFILLED = 'GET_MESSENGER_PROFILE_FULFILLED',
  GET_MESSENGER_PROFILE_REJECTED = 'GET_PROFILE_REJECTED',

  UPDATE_PROFILE_PIC = 'UPDATE_PROFILE_PIC',
  UPDATE_COVER_PIC = 'UPDATE_COVER_PIC',
  UPDATE_PROFILE_ACCOUNT = 'UPDATE_PROFILE_ACCOUNT',

  UPDATE_USER_NAME = 'UPDATE_USER_NAME',
  UPDATE_USER_FIRST_LOGIN = 'UPDATE_USER_FIRST_LOGIN',
  UPDATE_USER_NAME_FIRST_SCREEN = 'UPDATE_USER_NAME_FIRST_SCREEN',

  RESET = 'RESET',
  RESET_PENDING = 'RESET_PENDING',
  RESET_FULFILLED = 'RESET_FULFILLED',
  RESET_REJECTED = 'RESET_REJECTED',

  FORGET_PASSWORD = 'FORGET_PASSWORD',
  FORGET_PASSWORD_PENDING = 'FORGET_PASSWORD_PENDING',
  FORGET_PASSWORD_FULFILLED = 'FORGET_PASSWORD_FULFILLED',
  FORGET_PASSWORD_REJECTED = 'FORGET_PASSWORD_REJECTED',

  LOGOUT = 'LOGOUT',

  REFRESH_TOKEN = 'REFRESH_TOKEN',
  REFRESH_TOKEN_PENDING = 'REFRESH_TOKEN_PENDING',
  REFRESH_TOKEN_FULFILLED = 'REFRESH_TOKEN_FULFILLED',
  REFRESH_TOKEN_REJECTED = 'REFRESH_TOKEN_REJECTED',

  UPDATE_MESSENGER_INDICATOR = 'UPDATE_MESSENGER_INDICATOR',
}
